[project]
name = "very_holy_core"
version = "0.1.0"
authors = ["Justin Beaurivage <code@beaurivage.io>"]

[dependencies]
memutils = { version = "0.3.0", git = "https://github.com/jbeaurivage/memutils-veryl.git" }
uarty = { path = "../uarty" }

[build]
clock_type = "posedge"
reset_type = "async_low"

sources = ["src"]
target = { type = "directory", path = "target/veryl" }

[test]
waveform_target = { type = "directory", path = "target/waveform" }
waveform_format = "fst"
include_files = [
    "tb/test_cpu/test_dmem.hex",
    "tb/test_cpu/test_imem.hex",
    "tb/utils.py",
]