[project]
name = "very_holy_core"
version = "0.1.0"
authors = ["Justin Beaurivage <code@beaurivage.io>"]

[dependencies]
# memory = { path = "./memory" }
uarty = { path = "../uarty" }

[build]
clock_type = "posedge"
reset_type = "async_low"

sources = ["src"]
target = { type = "directory", path = "target/veryl" }

[test]
waveform_target = { type = "directory", path = "target/waveform" }
include_files = [
    "tb/test_cpu/test_dmem.hex",
    "tb/test_cpu/test_imem.hex",
    "tb/utils.py",
]